#version: 2.1
#
#jobs:
#  build:
#    docker:
#      - image: docker:17.03.0-ce
#    working_directory: /slackbot
#    branches:
#      only:
#        - master
#        - devlop
#    steps:
#      - setup_remote_docker
#      - run:
#          name: Show Info
#          command: |
#            docker version
#            docker info
#      - checkout
#      - run:
#          name: Build the current image
#          command: |
#            TAG=build
#            docker build -f Dockerfile -t ritsse/node-api:$TAG .
#      - run:
#          name: Distribute
#          command: |
#            docker login -u $DOCKER_USER -p $DOCKER_PASS
#            if [ "${CIRCLE_BRANCH}" == "master" ]; then
#                TAG=2.0.$CIRCLE_BUILD_NUM
#                docker tag ritsse/node-api:build ritsse/node-api:latest
#                docker tag ritsse/node-api:build ritsse/node-api:$TAG
#                docker push ritsse/node-api:$TAG
#                docker push ritsse/node-api:latest
#                JOB=deploy
#            else
#                TAG=dev-2.0.$CIRCLE_BUILD_NUM
#                docker tag ritsse/node-api:build ritsse/node-api:dev-latest
#                docker tag ritsse/node-api:build ritsse/node-api:$TAG
#                docker push ritsse/node-api:$TAG
#                docker push ritsse/node-api:dev-latest
#                JOB=dev_deploy
#            fi;
#            curl --user ${CIRCLE_API_TOKEN}: \
#                --data build_parameters[CIRCLE_JOB]=$JOB \
#                --data build_parameters[BUILD_TAG]=$TAG\
#                --data revision=$CIRCLE_SHA1 \
#                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
#
#  # Start deployment
#  dev_deploy:
#    machine: true
#    working_directory: ~/api
#    steps:
#      - add_ssh_keys
#      - deploy:
#          command: |
#            ssh deployer@eggs.se.rit.edu docker service update --image=ritsse/node-api:$BUILD_TAG sse_dev_dev_api_v2 --detach=false
#  deploy:
#    machine: true
#    working_directory: ~/api
#    steps:
#      - add_ssh_keys
#      - deploy:
#          command: |
#            ssh deployer@eggs.se.rit.edu docker service update --image=ritsse/node-api:$BUILD_TAG sse_api_v2 --detach=false
